language: go 

before_install:
  - go get -d github.com/graphite-ng/carbon-relay-ng
  - go get github.com/jteeuwen/go-bindata/...

install:
  - cd $HOME/gopath/src/github.com/graphite-ng/carbon-relay-ng
  - $HOME/gopath/bin/go-bindata admin_http_assets
  - go build

before_deploy:
  - tar -zcvf carbon-relay-ng.tar.gz carbon-relay-ng
  - cp carbon-relay-ng.tar.gz $HOME/gopath/src/github.com/TheCase/carbon-relay-ng_build/.
  - cd $HOME/gopath/src/github.com/TheCase/carbon-relay-ng_build

deploy:
  provider: releases
  api_key:
    secure: ORvMvzBqBlSzizH2BCWF7h3Dq2O9XzI8rVK0jpIFWsOSqJzD7cuTs63mIzzuG09L1/vfr3NS/d8aSgLw2BmumAxAVgmgtxBJeFqd6rGgrCte3yK4fWgRUsh9PKHKV2TrZ2qK2BESZEnJXrXUsgeIHNKRasrnulLrVrJgY6ZUzd4=
  file: carbon-relay-ng.tar.gz
  on:
    repo: TheCase/carbon-relay-ng_build
    tags: true
    all_branches: true
